name: Go

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./cmd/...

      - name: vet
        run: go vet ./...

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: "-l -d"

      - name: Revive Action
        uses: morphy2k/revive-action@v2.7.4

      - name: Tests
        run: go test -v ./...

  run_modver:
      runs-on: ubuntu-latest
      needs: build # Only run when build job was successful
      if: ${{ github.event_name == 'pull_request' && success() }}
      permissions:
        contents: read # Modver needs to read the repo content
        pull-requests: write # Modver needs to write comments/status on PRs
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Modver needs full history for comparison

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: "stable"

        - name: Modver
          uses: bobg/modver@v2.11.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
