name: Integration tests
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.6"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute the scripts
        run: |
          sudo apt update
          sudo apt install -y make nginx fcgiwrap gnutls-bin
          cp -r $GITHUB_WORKSPACE ~
          cd ~
          cd csaf/docs/scripts/
          # keep in sync with docs/scripts/Readme.md
          export FOLDERNAME=devca1 ORGANAME="CSAF Tools Development (internal)"
          source ./TLSConfigsForITest.sh
          ./TLSClientConfigsForITest.sh
          ./setupProviderForITest.sh
          ./testAggregator.sh
          ./testDownloader.sh
        shell: bash

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: checker-results
          path: |
            ~/checker-results.html
            ~/checker-results-no-clientcert.json
          if-no-files-found: error
