name: Publish Go binaries to github release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go binaries
    # use oldest available ubuntu to be compatible with more libc.so revs.
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
            go-version: '^1.24.9'
            check-latest: true

      - name: Build
        run: make dist

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
            files: |
                dist/csaf-*.zip
                dist/csaf-*.tar.gz
