name: Publish Go binaries to github release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go binaries
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '^1.23.6'

      - name: Build
        run: make dist

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
            files: |
                dist/csaf-*.zip
                dist/csaf-*.tar.gz
